### PR TITLE
refactor: another attempt for different session ids

### PR DESCRIPTION
**Pull request by kgilmer**

### CODE REVIEW

**Comment by kgilmer** [comment]
In testing, X11 session loads but the UI does not update.  Do not see anything in the logs that points to a rootcause.  Continuing to troubleshoot.

**Comment by kgilmer** [comment]
I opted to do some testing on physical hardware and am not seeing the issues I was seeing in a vm.  :face_exhaling:

**Comment by kgilmer** [comment]
This change and the associated change in `xdg-desktop-portal-regolith` can be tested by installing from `unstable`.  You can verify w/ the package versions decl in changelog.

**Comment by SoumyaRanjanPatnaik** [comment]
Hey. I'll test and let you know any findings I have after fiddling around with this PR.

**Comment by SoumyaRanjanPatnaik** [comment]
Things work on the Wayland side of things. As expected, the `xdp-wlr` backend is being used for screen sharing.

**Comment by SoumyaRanjanPatnaik** [comment]
> In testing, X11 session loads but the UI does not update. Do not see anything in the logs that points to a rootcause. 

However, the X11 session does have the issue you're describing. For me, the session crashes with gnome's "Something went wrong" screen. This has been happening for a while now (even when I didn't have these changes installed). This has been one of the reasons I haven't been able to test the X11 session for quite some time now.

I wonder if you made some changes in your local system that you forgot to push.

BTW, if this is irrelevant to this PR, we can create a separate issue to discuss. The PR looks good to me and I think it is unlikely the cause.

**Review by SoumyaRanjanPatnaik — APPROVED** [review]

**Pull request merged**
